development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: amanc
  pool: 5
  username: amanc
  password: beans
  
production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: pddma1017131
  pool: 5
  username: "1017131_user"
  password: "1017131"
  
